=== Rocioizv/LMSGI/xml/Proyecto XML/proyecto.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="curriculum" type="T_CV">

    </xs:element>
    <xs:complexType name="T_CV">
        <xs:sequence>
            <xs:element name="datosPersonales" type="T_datosP" />
            <xs:element name="datosContacto" type="T_datosC" />
            <xs:element name="datosContactoA" type="T_datosCA" />
            <xs:element name="forAcademica" type="T_forAcademica" />
            <xs:element name="idiomas" type="T_idiomas" />
            <xs:element name="expLaboral" type="T_expLaboral" />
            <xs:element name="compSocPer" type="T_compSocPer" />
            <xs:element name="datosAdicionales" type="T_datosAdic" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="T_datosP">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string" />
            <xs:element name="apellidos" type="xs:string" />
            <xs:element name="fechaNac" type="xs:date" />
            <xs:element name="lugarNac" type="xs:string" />
            <xs:element name="nacionalidades" type="xs:string" />
            <xs:element name="nie" type="T_nie" />
        </xs:sequence>

    </xs:complexType>

    <xs:simpleType name="T_nie">
        <xs:restriction base="xs:string">
            <xs:pattern value="[XYZ]\d{7}[A-Z]" />
        </xs:restriction>
    </xs:simpleType>


    <xs:complexType name="T_datosC">
        <xs:sequence>
            <xs:element name="tipoVia" type="xs:string" />
            <xs:element name="nombreVia" type="xs:string" />
            <xs:element name="numeroVia" type="xs:integer" minOccurs="0" />
            <xs:element name="portal" type="xs:integer" minOccurs="0" />
            <xs:element name="escalera" type="xs:integer" minOccurs="0" />
            <xs:element name="piso" type="xs:integer" minOccurs="0" />
            <xs:element name="puerta" type="xs:string" minOccurs="0" />
            <xs:element name="cp" type="T_cp" />
            <xs:element name="pais" type="xs:string" />
            <xs:element name="email" type="T_email" />
            <xs:element name="telfMovil" type="T_numTelefono" />
            <xs:element name="telfFijo" type="T_numTelefono" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="T_cp">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{5}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="T_email">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="T_numTelefono">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{9}" />
        </xs:restriction>
    </xs:simpleType>


    <xs:complexType name="T_datosCA">
        <xs:sequence>
            <xs:element name="pagWeb" type="xs:string" minOccurs="0" />
            <xs:element name="redesSociales" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="T_forAcademica">
        <xs:sequence>
            <xs:element name="nombreEstudio" type="xs:string" />
            <xs:element name="lugarEstudio" type="xs:string" />
            <xs:element name="fechaInicio" type="xs:date" />
            <xs:element name="fechaFin" type="xs:date" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="T_idiomas">
        <xs:sequence>
            <xs:element name="nomIdioma" type="xs:string" />
            <xs:element name="nivelOral" type="T_nivelIdioma" minOccurs="0" />
            <xs:element name="nivelComprensionO" type="T_nivelIdioma" />
            <xs:element name="nivelEscrito" type="T_nivelIdioma" minOccurs="0" />
            <xs:element name="nivelComprensionE" type="T_nivelIdioma" />
            <xs:element name="titulo" type="xs:string" />
            <xs:element name="nivelTitulo" type="T_nivelTitulo" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="T_nivelIdioma">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Bajo" />
            <xs:enumeration value="Medio" />
            <xs:enumeration value="Alto" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="T_nivelTitulo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A1" />
            <xs:enumeration value="A2" />
            <xs:enumeration value="B1" />
            <xs:enumeration value="B2" />
            <xs:enumeration value="C1" />
            <xs:enumeration value="C2" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="T_expLaboral">
        <xs:sequence>
            <xs:element name="lugarExp" type="xs:string" />
            <xs:element name="puesto" type="xs:string" />
            <xs:element name="fechaInicio" type="xs:string" />
            <xs:element name="fechaFin" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="T_compSocPer">
        <xs:sequence>
            <xs:element name="competencia">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string" />
                        <xs:element name="nivel" type="T_nivelComp" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="T_nivelComp">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1" />
            <xs:maxInclusive value="5" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="T_datosAdic">
        <xs:sequence>
            <xs:element name="aficiones" type="xs:string" />
            <xs:element name="disponViaje" type="xs:string" />
            <xs:element name="vehiculo" type="xs:string" />
            <xs:element name="permisoConducir" type="T_licenciaCond" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="T_licenciaCond">
        <xs:restriction base="xs:string">
            <xs:enumeration value="AM" />
            <xs:enumeration value="A1" />
            <xs:enumeration value="A2" />
            <xs:enumeration value="A" />
            <xs:enumeration value="B" />
            <xs:enumeration value="B+E" />
            <xs:enumeration value="C1" />
            <xs:enumeration value="C" />
            <xs:enumeration value="D1" />
            <xs:enumeration value="D1+E" />
            <xs:enumeration value="D" />
            <xs:enumeration value="BTP" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Rocioizv/LMSGI/xml/proyecto.xml
<?xml version="1.0" encoding="utf-8"?>
<curriculum  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="proyecto.xsd">

  
  <datosPersonales>
    <nombre>Rocio</nombre>
    <apellidos>Contarino Cannobbio</apellidos>
    <fechaNac>2005-06-15</fechaNac>
    <lugarNac>España</lugarNac>
    <nacionalidades>española, argentina</nacionalidades>
    <nie>X1234567T</nie>

  </datosPersonales>

  <datosContacto>
    <tipoVia>tipoVia</tipoVia>
    <nombreVia>nombre</nombreVia>
    <numeroVia>56</numeroVia>
    <portal>2</portal>
    <escalera>3</escalera>
    <piso>2</piso>
    <puerta>A</puerta>
    <cp>18290</cp>
    <pais>España</pais>
    <email>nombre@gmail.com</email>
    <telfMovil>123456789</telfMovil>
    <telfFijo>123456789</telfFijo>
  </datosContacto>

  <datosContactoA>
    <pagWeb></pagWeb>
    <redesSociales></redesSociales>
  </datosContactoA>

  <forAcademica>
    <nombreEstudio></nombreEstudio>
    <lugarEstudio></lugarEstudio>
    <fechaInicio>2000-01-01</fechaInicio>
    <fechaFin>2000-10-01</fechaFin>
  </forAcademica>

  <idiomas>
    <nomIdioma></nomIdioma>
    <nivelOral>Medio</nivelOral>
    <nivelComprensionO>Medio</nivelComprensionO>
    <nivelEscrito>Alto</nivelEscrito>
    <nivelComprensionE>Alto</nivelComprensionE>
    <titulo></titulo>
    <nivelTitulo>B2</nivelTitulo>
  </idiomas>

  <expLaboral>
    <lugarExp></lugarExp>
    <puesto></puesto>
    <fechaInicio></fechaInicio>
    <fechaFin></fechaFin>
  </expLaboral>

  <compSocPer>
    <nombre></nombre>
    <nivel>4</nivel>
  </compSocPer>

  <datosAdicionales>
    <aficiones></aficiones>
    <disponViaje></disponViaje>
    <vehiculo></vehiculo>
    <permisoConducir>B</permisoConducir>
  </datosAdicionales>

</curriculum>

=== Rocioizv/LMSGI/xml/Proyecto XML/proyecto.xml
<?xml version="1.0" encoding="utf-8"?>
<curriculum  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="proyecto.xsd">

  
  <datosPersonales>
    <nombre>Rocio</nombre>
    <apellidos>Contarino Cannobbio</apellidos>
    <fechaNac>2005-06-15</fechaNac>
    <lugarNac>España</lugarNac>
    <nacionalidades>española</nacionalidades>
    <nie>X1234567T</nie>

  </datosPersonales>

  <datosContacto>
    <tipoVia>tipoVia</tipoVia>
    <nombreVia>nombre</nombreVia>
    <numeroVia>5</numeroVia>
    <portal>2</portal>
    <escalera>3</escalera>
    <piso>2</piso>
    <puerta>A</puerta>
    <cp>18290</cp>
    <pais>España</pais>
    <email>nombre@gmail.com</email>
    <telfMovil>123456789</telfMovil>
    <telfFijo>123456789</telfFijo>
  </datosContacto>

  <datosContactoA>
    <pagWeb>librosycafe.com</pagWeb>
    <redesSociales>aa</redesSociales>
  </datosContactoA>

  <forAcademica>
    <nombreEstudio>DAW</nombreEstudio>
    <lugarEstudio>ies zaidin vergeles</lugarEstudio>
    <fechaInicio>2000-01-01</fechaInicio>
    <fechaFin>2000-10-01</fechaFin>
  </forAcademica>

  <idiomas>
    <nomIdioma>Inglés</nomIdioma>
    <nivelOral>Medio</nivelOral>
    <nivelComprensionO>Medio</nivelComprensionO>
    <nivelEscrito>Alto</nivelEscrito>
    <nivelComprensionE>Alto</nivelComprensionE>
    <titulo></titulo>
    <nivelTitulo>B2</nivelTitulo>
  </idiomas>

  <expLaboral>
    <lugarExp>ee</lugarExp>
    <puesto>ee</puesto>
    <fechaInicio></fechaInicio>
    <fechaFin></fechaFin>
  </expLaboral>

  <compSocPer>
    <competencia>
    <nombre>trabajo en equipo</nombre>
    <nivel>4</nivel>
    </competencia>
  </compSocPer>

  <datosAdicionales>
    <aficiones></aficiones>
    <disponViaje></disponViaje>
    <vehiculo></vehiculo>
    <permisoConducir>B</permisoConducir>
  </datosAdicionales>

</curriculum>
